### ISSUE TITLE
Add an option to use/not use Docker.

### ISSUE THREAD

**Issue by terjekv** [terjekv/ansible-role-github-authorized-keys#7]
Ideally one would be able to do something like:

```yaml
{ role: terjekv.github_authorized_keys,
  use_docker: [True/False],
  github_organization: "myorg",
  ... }
```
